# NOTE: update this with your service name
service: notes-api

custom:
  # for serverless-bundle -- webpack wrapper
  bundle:
    sourcemaps: true      # Enable source maps
    caching: false        # While in development don't cache
    stats: false          # Don't print out any Webpack output
    linting: false        # Disable linting as a part of the build process

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}
  environment:
    tableName: notes
    stripeSecretKey: ${env:STRIPE_SECRET_KEY}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  create:
    handler: lambda-functions/create.main
    events:
      - http:
          path: notes
          method: post
          authorizer: aws_iam
  get:
    handler: lambda-functions/get.main
    events:
      - http:
          path: notes/{id}
          method: get
          authorizer: aws_iam
  list:
    handler: lambda-functions/list.main
    events:
      - http:
          path: notes
          method: get
          authorizer: aws_iam
  update:
    handler: lambda-functions/update.main
    events:
      - http:
          path: notes/{id}
          method: put
          authorizer: aws_iam
  delete:
    handler: lambda-functions/delete.main
    events:
      - http:
          path: notes/{id}
          method: delete
          authorizer: aws_iam
  billing:
    handler: lambda-functions/billing.main
    events:
      - http:
          path: billing
          method: post
          authorizer: aws_iam
